sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - CGMethodTest

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false